{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: n8n-env
  labels:
    app.kubernetes.io/name: n8n
type: Opaque
stringData:
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
