apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Monitoring:
        - Grafana:
            icon: grafana
            href: https://grafana.devops-lab.dev
            description: Grafana is the best

        - Prometheus:
            icon: prometheus
            href: https://prometheus.devops-lab.dev
            description: Prometheus is the best

        - Alertmanager:
            icon: alertmanager
            href: https://alert.devops-lab.dev
            description: Alertmanager is the best
    - Observability:
        - Loki:
            icon: loki
            href: https://loki.devops-lab.dev
            description: Loki is the best

    - Splunk:
        - Splunk Standalone:
            icon: splunk
            href: https://standalone.devops-lab.dev
            description: Splunk Standalone instance

        - Monitoring Console:
            icon: splunk SHC
            href: https://splunk.devops-lab.dev
            description: Splunk Search Head instance
    - Kubernetes:
        - K8s Dashboard:
            icon: kubernetes
            href: https://k8s.devops-lab.dev
            description: K8s Dashboard is the best

        - K9s:
            icon: terminal
            href: https://k9s.devops-lab.dev
            description: K9s is the best

    - Networking:
        - Kong Manager:
            icon: kong
            href: https://kong.devops-lab.dev
            description: Kong Manager is the best

        - Cloudflare Zero Trust:
            icon: cloudflare
            href: https://dash.cloudflare.com
            description: Cloudflare Zero Trust is the best
    - Services:
        - Homepage:
            icon: homepage
            href: https://home.devops-lab.dev
            description: Homepage is the best
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""