all:
  vars:
    ansible_user: test
    ansible_become: true
  children:
    controllers:
      hosts:
        controller:
          ansible_host: 10.0.0.198
          ansible_user: devops
          ansible_ssh_pass: "{{ vault_controller_ssh_pass }}"
    registry:
      hosts:
        nexus:
          ansible_host: 10.0.0.110
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
    k3s_masters:
      hosts:
        k3s-master:
          ansible_host: 10.0.0.102
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
    k3s_workers:
      hosts:
        k3s-worker-A:
          ansible_host: 10.0.0.104
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
        k3s-worker-B:
          ansible_host: 10.0.105
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
        k3s-worker-C:
          ansible_host: 10.0.0.106
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
