- name: Fetch kubeconfig from master and place on controller
  hosts: k3s_masters
  gather_facts: false
  tasks:
    - name: Slurp k3s kubeconfig
      become: true
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kcfg

    - name: Set fact with updated server endpoint
      set_fact:
        kubeconfig_content: "{{ (kcfg.content | b64decode) | regex_replace('127.0.0.1', hostvars[inventory_hostname].ansible_host) }}"

    - name: Copy kubeconfig to controller
      delegate_to: controller
      become: true
      copy:
        content: "{{ kubeconfig_content }}"
        dest: "{{ kubeconfig_local_path }}"
        owner: devops
        group: devops
        mode: '0600'
      run_once: true
