---
- name: Deploy Splunk License Manager (CRD)
  hosts: controller
  gather_facts: false

  vars:
    _name: "{{ splunk_license_manager_name | default('splunk-license-manager') }}"
    _ns: "{{ splunk_namespace | default('splunk') }}"
    k8s_kubeconfig: "/home/devops/.kube/config"

  tasks:
    # Apply the Splunk License Manager CR
    - name: Apply Splunk License Manager CR (accept license, imagePullSecrets, etc.)
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_kubeconfig }}"
        template: "../roles/splunk_crd/templates/license-manager.yml.j2"

    # Wait for the Splunk License Manager pod to be ready
