---
- name: Deploy Splunk Cluster Manager
  hosts: controller
  gather_facts: false

  vars:
    _ns: "{{ splunk_namespace | default('splunk') }}"
    k8s_kubeconfig: "{{ kubeconfig_local_path | default('/home/devops/.kube/config') }}"

  tasks:
    - name: Apply Cluster Manager CR
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_kubeconfig }}"
        template: "../roles/splunk_crd/templates/cluster-manager.yml.j2"
