trigger: none     # ❗ EXÉCUTION MANUELLE SEULEMENT

pool:
  name: LabAgents   # Le nom de ton agent self-hosted

variables:
  - group: LabSecret   # Ton Variable Group contenant vault_ansible_ssh_pass
  - name: PLAYBOOK_PATH
    value: "infrastructure/ansible/playbooks/05-change-hostname.yml"
  - name: INVENTORY_PATH
    value: "infrastructure/ansible/inventories/hosts.yml"
  - name: ANSIBLE_CONFIG
    value: "infrastructure/ansible/ansible.cfg"

steps:
  - checkout: self

  - script: |
      echo "=== RUNNING change-hostname.yml playbook ==="
      cd $(System.DefaultWorkingDirectory)
      ansible-playbook ${PLAYBOOK_PATH} \
      -i $(System.DefaultWorkingDirectory)/infrastructure/ansible/inventories/hosts.yml \
      -e "vault_ansible_ssh_pass=$(vault_ansible_ssh_pass)"
    displayName: "Run Change Hostname playbook"
